# Generated by Django 2.0.3 on 2018-08-10 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='amout',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='expense',
            name='poject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='budgetApp.Project'),
        ),
    ]
