# Generated by Django 2.0.3 on 2018-08-22 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetApp', '0002_auto_20180810_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='poject',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='poject',
            new_name='project',
        ),
    ]
